# Generated by Django 4.2.1 on 2023-05-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
